### PR TITLE
Add disabling action events

### PR DESCRIPTION
**Pull request by dillingham**

### CODE REVIEW

**Comment by dkulyk** [comment]
Also user can disable it in resource
`(new SomeAction)->withoutActionEvents()`

**Comment by dillingham** [comment]
@dkulyk added 👍

**Comment by taylorotwell** [comment]
What does this actually do?

**Comment by taylorotwell** [comment]
Also, every sentence preceding an example in the documentation ends with a `:`

**Comment by dillingham** [comment]
@taylorotwell made it more clear, hopefully, and added `:`

**Comment by dillingham** [comment]
Ah you're right, doesn't really even define it. I'll take a stab at it

**Comment by taylorotwell** [comment]
Eh, nevermind, you didn't have to rewrite all my text :smile: ... Extracted the relevant parts and merged.

**Pull request closed without merging**
